# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\z003vrzk\.spyder-py3\Scripts\Work\PanelBuilder\panel-builder\panel_builder_pyqt\src\main\ui designer\QDialog Options.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OptionsDialog(object):
    def setupUi(self, OptionsDialog):
        OptionsDialog.setObjectName("OptionsDialog")
        OptionsDialog.setEnabled(True)
        OptionsDialog.resize(400, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OptionsDialog.sizePolicy().hasHeightForWidth())
        OptionsDialog.setSizePolicy(sizePolicy)
        OptionsDialog.setMinimumSize(QtCore.QSize(400, 200))
        OptionsDialog.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        OptionsDialog.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(OptionsDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.SQLHostLabel = QtWidgets.QLabel(OptionsDialog)
        self.SQLHostLabel.setObjectName("SQLHostLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.SQLHostLabel)
        self.ProductDBLabel = QtWidgets.QLabel(OptionsDialog)
        self.ProductDBLabel.setObjectName("ProductDBLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ProductDBLabel)
        self.SQLDriverLabel = QtWidgets.QLabel(OptionsDialog)
        self.SQLDriverLabel.setObjectName("SQLDriverLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.SQLDriverLabel)
        self.JobFolderLabel = QtWidgets.QLabel(OptionsDialog)
        self.JobFolderLabel.setObjectName("JobFolderLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.JobFolderLabel)
        self.comboBox = QtWidgets.QComboBox(OptionsDialog)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.JobFolderText = QtWidgets.QTextEdit(OptionsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JobFolderText.sizePolicy().hasHeightForWidth())
        self.JobFolderText.setSizePolicy(sizePolicy)
        self.JobFolderText.setObjectName("JobFolderText")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.JobFolderText)
        self.ProductDBText = QtWidgets.QTextEdit(OptionsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProductDBText.sizePolicy().hasHeightForWidth())
        self.ProductDBText.setSizePolicy(sizePolicy)
        self.ProductDBText.setObjectName("ProductDBText")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ProductDBText)
        self.SQLHostText = QtWidgets.QTextEdit(OptionsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SQLHostText.sizePolicy().hasHeightForWidth())
        self.SQLHostText.setSizePolicy(sizePolicy)
        self.SQLHostText.setObjectName("SQLHostText")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.SQLHostText)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(OptionsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(OptionsDialog)
        self.buttonBox.accepted.connect(OptionsDialog.accept)
        self.buttonBox.rejected.connect(OptionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialog)

    def retranslateUi(self, OptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        OptionsDialog.setWindowTitle(_translate("OptionsDialog", "Options"))
        self.SQLHostLabel.setText(_translate("OptionsDialog", "SQL Server Host"))
        self.ProductDBLabel.setText(_translate("OptionsDialog", "Products Database Folder"))
        self.SQLDriverLabel.setText(_translate("OptionsDialog", "SQL Driver Name"))
        self.JobFolderLabel.setText(_translate("OptionsDialog", "Default Jobs Folder"))

